version: "3.9"
services:
  ut99-server:
    image: roemer/ut99-server:latest
    volumes:
      - ut99-data:/ut-data
    ports:
      - 5580:5580/tcp
      - 7777:7777/udp
      - 7778:7778/udp
      - 7779:7779/udp
      - 7780:7780/udp
      - 7781:7781/udp
      - 8777:8777/udp
      - 27900:27900/tcp
      - 27900:27900/udp
    environment:
      - UT_SERVERURL="DM-Morpheus?game=Botpack.DeathMatchPlus?mutators=BotPack.InstaGibDM,MapVoteLAv2.BDBMapVote"
      - UT_MINPLAYERS_DM=2
      - UT_MINPLAYERS_CTF=8
      - UT_INITIALBOTS_DM=2
      - UT_INITIALBOTS_CTF=8
      - UT_DOUPLINK=False
      - UT_SERVERNAME
      - UT_ADMINNAME
      - UT_ADMINEMAIL
      - UT_MOTD1
      - UT_ADMINPWD
      - UT_WEBADMINUSER
      - UT_WEBADMINPWD
    expose:
      - "5580"
      - "7777"
      - "7778"
    restart: unless-stopped
  ut99-discord:
    build:
      context: .
      dockerfile: Dockerfile.discord
    restart: unless-stopped
    depends_on:
    - "ut99-server"
volumes:
  ut99-data: